### ISSUE TITLE
USB Power Issues - charging on iPad(s) and iPhoneX and above

### ISSUE THREAD

**Issue by Sniki** [Sniki/Lenovo-Thinkpad-X240#1]
There is a problem with iPads or iPhones where if you plug it on any of the ports it will connect and disconnect infinitely.
One port may seem to charge it but if you check on the IORegistryExplorer, you will see that it keeps connecting and disconnecting infinitely and the other(s) port(s) will be noticeable by checking the iPhone or iPad changing icon every second.

I did check the XHCI device in DSDT and it seems that there are many things that can cause the issue.
Will do some more in-depth testing in Linux and Windows to assure that it is not a hardware issue and if not start testing.

**Comment by JY-DB** [comment]
No problem in windows10 and linux
I have encountered the problem you mentioned in macos big sur
Mobile phone use iphone6s plus

**Comment by Sniki** [comment]
> No problem in windows10 and linux
> I have encountered the problem you mentioned in macos big sur
> Mobile phone use iphone6s plus

Yes, i will look into this when i have more time.
There are many things happening into XHCI after checking the ACPI so i will have to check what is interfering with the ports

**Comment by Silfalion** [comment]
My ipad and iphone connect well too. Maybe it’s a hardware problem like the cable or the ports?

**Comment by Sniki** [comment]
Confirmed as hardware problem/limitation, it happens on Windows and Linux as well and not just on my laptops, the entire line-up suffers from this.
