### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by ghost** [Sniki/Lenovo-Thinkpad-X240#10]
1. the headset still have base sound after installing the fix driver
2. the brightness control key in keyboard doesn't work(it shows the icon in the screen, but the brightness of monitor actually no change.(after x240 sleeps, the problem fixs.)

**Comment by ghost** [comment]
also, the bluetooth of wireless n7260 isn't work

**Comment by Sniki** [comment]
First please use the guide into the tmx86 for troubleshooting problems.

1. I am working into a fix for ALCPlugFix
2. Brightness control works, installed yesterday on my X240 and it’s working fine.
3. Wireless AC7260 works fine.

Double check your work

**Comment by ghost** [comment]
![螢幕截圖 2021-03-23 下午5 04 08](https://user-images.githubusercontent.com/74304366/112121157-e335bf00-8bf9-11eb-8557-c877f34c5970.png)
![螢幕截圖 2021-03-23 下午5 05 24](https://user-images.githubusercontent.com/74304366/112121226-f8125280-8bf9-11eb-800a-a98dd2883c83.png)
I asked the creator of the kexts of IntelBluetoothFirmware, he told me that even there are no the kexts, the bluetooth devices should be shown
However, I use Hackintosh tool to check. there is not any bluetooth devices

**Comment by ghost** [comment]
Thanks for your nice answer and sorry for my poor English.

**Comment by Sniki** [comment]
Ask for help here: https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-6-7-wip.311503/
Upload EFI so we can check what is the problem, im at work right now, will check on evening

**Comment by ghost** [comment]
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-6-7-wip.311503/post-2237179
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-6-7-wip.311503/post-2237181

**Comment by MilkyPL** [comment]
Sound can be fixed by adding `alcverbs=1` to boot-args.
![image](https://user-images.githubusercontent.com/20266576/112149876-be345280-8bdf-11eb-8074-7c295b6d296c.png)

**Comment by ghost** [comment]
> Sound can be fixed by adding `alcverbs=1` to boot-args.
> ![image](https://user-images.githubusercontent.com/20266576/112149876-be345280-8bdf-11eb-8074-7c295b6d296c.png)

it fixes the problem. Thanks you. But the microphone input by headphone isn't work properly(some zizizi sound in the background when I record).

**Comment by Sniki** [comment]
@MilkyPL can you provide more informations on how to use alcverbs=1 ?, will it work just by adding this boot-arg as it didn't fix the audio for me just by that.
Acidanthera/AppleALC documentation/wiki hasn't been updated for a while and no clear documentation on how to use it is done.

I still have the static sound with alcverbs=1, there is also the DeviceProperty alc-verbs but no clear documentation on how it works, what it does or how to implement it is done on their side.

**Comment by MilkyPL** [comment]
@Sniki I just added it to boot-args and rebooted, nothing else. I don't even know how DeviceProperties work, I guess someone should open an issue in the AppleALC repo about it.
Maybe try reinstalling the ALCPlugFix?

**Comment by MilkyPL** [comment]
Nevermind, just saw the latest commit, nice job

**Comment by Sniki** [comment]
@MilkyPL after some deeper researches i noticed that AppleALC needs the alc-verbs device property or the alcverbs=1 boot-arg in order to accept incoming custom commands from 3rd party apps/tools like CodecCommander, ALCPlugFix, etc.

Fixed in master, Thanks !

**Comment by ghost** [comment]
Hi Sniki, did you add any DSDT patches or ACPI patches to help BrightnessKeys.kext to work properly?
I want to edit the kext to make it work on my x240 (replaced a monitor).
