### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by ghost** [Sniki/Lenovo-Thinkpad-X240#11]
Sorry, Sniki. I try to solve the problem of Bluetooth in big sur for a week, but it doesn't work.
![UsbTreeView](https://user-images.githubusercontent.com/74304366/113139060-31ca0580-9259-11eb-9c68-84d6257a6b55.png)
![BT_device manager](https://user-images.githubusercontent.com/74304366/113139070-34c4f600-9259-11eb-8827-536a4d64a50d.png)
![Wifi_device manager](https://user-images.githubusercontent.com/74304366/113139074-35f62300-9259-11eb-8500-972b671c61cd.png)
![Hackintool](https://user-images.githubusercontent.com/74304366/113139085-38f11380-9259-11eb-8392-11690fe2ef3b.png)
![IORegistryExplorer](https://user-images.githubusercontent.com/74304366/113139088-3a224080-9259-11eb-9503-5712606369d5.png)
![USB_mac](https://user-images.githubusercontent.com/74304366/113139097-3bec0400-9259-11eb-8f6c-2e0f3856a7c1.png)
![BT_mac](https://user-images.githubusercontent.com/74304366/113139101-3e4e5e00-9259-11eb-93eb-a5a401818351.png)
The efi folder ,full description and Bluetooth_UsbTreeView.txt are attached here"https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-6-7-wip.311503/post-2238744"

**Comment by Sniki** [comment]
You already wrote on the forum, will check it once i have some time.

**Comment by ghost** [comment]
https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240.245583/
refer to the above guide, written by you.
i cannot reset the nvram, but my oc version is wrong now. How can i clean nvram than reset

**Comment by copws** [comment]
USBInjectAll.kext is useful
