### ISSUE TITLE
Brightness not working

### ISSUE THREAD

**Issue by nalakawula** [Sniki/Lenovo-Thinkpad-X240#13]
The function button to set brightness is working but screen brightness is still. For example when I lower the brightness the screen is not dimmed.

I use High Sierra in Thinkpad x240 with latest bios version.

Thanks

**Comment by itsdanang** [comment]
> The function button to set brightness is working but screen brightness is still. For example when I lower the brightness the screen is not dimmed.
> 
> I use High Sierra in Thinkpad x240 with latest bios version.
> 
> Thanks

Brightness is working, but you have to lock the laptop first and then once it got the lock screen click the cancel as it makes the screen turn off. Wake the screen again, and then voila you can now change the brightness.

**Comment by nalakawula** [comment]
it's complicated, any other ways to fix? maybe checking the patched acpi

**Comment by enochluo** [comment]
hi @nalakawula, i met the same problem before. https://www.tonymacx86.com/threads/guide-lenovo-thinkpad-x240-opencore-0-6-7-wip.311503/post-2242029. Here is my solution. I hope it works now, because it was long time ago.

**Comment by Sniki** [comment]
Planning a future update and will address some of the know issues and bring some additional enhancements.
