### ISSUE TITLE
Intel Wifi problem, and Monterey possibility?

### ISSUE THREAD

**Issue by itsdanang** [Sniki/Lenovo-Thinkpad-X240#14]
sometimes wi-fi connected but it will have "!" mark, i have to reconnect a few times just to get it working, is it happening to you? anyway, i've tried to install Monterey with your EFI by changing SMBIOS to MacBookPro12,1 and it works (HD 4400 still works somehow)i hope you still maintain this EFI when Monterey released, many thanks!

**Comment by Sniki** [comment]
I will have to see how Monterey works, there are a lot of other things that are necessary to have a proper working configuration than just graphics itself, if it's just an SMBIOS spoof/change, then that should be fine and will update to that.

However i do plan to make an update in the near future with latest OpenCore and some additional enhancements and bugfixes.
