### ISSUE TITLE
Post Installation First Boot issue

### ISSUE THREAD

**Issue by DhruvMuke** [Sniki/Lenovo-Thinkpad-X240#15]
Hey! thanks for the EFI. I just wanted to know if theres any problem with the Audio. It seems like the audio output on my laptop is very low. Might be a speaker issue, but yeah. The EFI works perfectly for me. But I used a HDD instead of an SSD. I was wondering would that be the reason why the experience feels really slow. Ram might also be the issue as I havent upgraded it at all. I will swap out for an 8GB stick in a while. But, should I stick to the SSD? Thanks

**Comment by DhruvMuke** [comment]
Also, I would have to generate a new SMBIOS to make iServices work right? Im sorry lol.

**Comment by Sniki** [comment]
to be honest HDD is a nightmare experience on any PC/laptop, try to get an SSD and see how much of a life changer it is.
Audio is a bit low in general but for now there is no actual fix to that.
