### ISSUE TITLE
Boots into recovery after finishing installation

### ISSUE THREAD

**Issue by lazydevyo** [Sniki/Lenovo-Thinkpad-X240#17]
There's no Mac OS hard drive boot option by default, Selecting the USB with open core and then the hard drive where it was installed boots back to recovery, no idea why. then the drive disappears and there's only the USB stick. help would be appreciated,

**Comment by Sniki** [comment]
You most likely forgot HfsPlus.efi driver or removed it, everything works fine as per guide till the project supported as per readme page, what is past big sur 11.2.3 and oc 0.6.7 i can't help with that.

Planning a future update and everything should be supported to the latest versions.
