### ISSUE TITLE
You can try the OC beta build

### ISSUE THREAD

**Issue by JY-DB** [Sniki/Lenovo-Thinkpad-X240#5]
You can try the OC test version build and then use the debug version

https://github.com/williambj1/OpenCore-Factory

Thank you very much

(My english is not good, sorry)

**Comment by Sniki** [comment]
> You can try the OC test version build and then use the debug version
> 
> https://github.com/williambj1/OpenCore-Factory
> 
> Thank you very much
> 
> (My english is not good, sorry)

Thanks for the hint.

But i will only add and support release builds as I don’t have time for daily builds.

**Comment by JY-DB** [comment]
Is there any teaching, I want to try to configure OC, if successful, I can submit it to you
